FROM envoyproxy/envoy:latest

RUN apt-get update && apt-get -q install -y \
    curl
RUN apt-get -q install -y iputils-ping
RUN apt-get -q install -y net-tools
CMD /usr/local/bin/envoy -c /etc/front-envoy.yaml --service-cluster front-proxy
